### ISSUE TITLE
PSN Not working

### ISSUE THREAD

**Issue by otDan** [borger/scoop-galaxy-integrations#16] opened 2021-07-14 15:38 UTC
![image](https://user-images.githubusercontent.com/59731738/125650552-b0c282f0-ff37-47b2-a8e5-cb56628f1565.png)
The playstation network integration is not working.

**Comment by borger** [comment] 2021-07-18 15:46
Hello @otDan thank you for opening this issue. This seem to be related with the package itself, as you can see here: https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/25 

I'll see if there's any workaround that. Keep you posted.

**Comment by borger** [comment] 2021-07-20 19:18
Apparently, the issue is known and a fix is in the works, we just have to give it some time. Sony has implemented some new APIs, and the integration needs to be updated. 
https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/25#issuecomment-883199020

**Comment by borger** [comment] 2021-09-10 23:46
This issue has been fixed as reported in the links above.

**Closed as completed by borger** 2021-09-10 23:46 UTC
